spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: OMS-Service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.61.140:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.136:3306/OMS?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


server:
  port: 3000


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.buck.apache.dubbo.provider.mapper: debug

mybatis-plus:
  type-aliases-package: com.buck.apache.dubbo.provider.entity
  mapper-locations: classpath:mapper/*.xml